import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CartProvider } from "@/app/context/CartContext";
import Header from "./components/Header";
import { ToastContainer, toast, Slide } from "react-toastify";

import "react-toastify/dist/ReactToastify.css";
import Footer from "./components/Footer";
import Script from "next/script";
import { Suspense } from "react";
import { Analytics } from "@vercel/analytics/react"


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata:Metadata = {
  title: "HomeCene | Premium Home Decor, Mirrors, Vases & Lamps in Dubai – Elevate Your Space",
  description: "Discover Homecene, Dubai’s premier destination for luxury home decor, mirror vases, lamps, and stylish furniture. Transform your space with elegant designs and smart home essentials. Fast delivery across the UAE!",
  icons: [
    { rel: "icon", type: "image/x-icon", url: "/favicon.ico" }, // Favicon
    { rel: "apple-touch-icon", url: "/apple-touch-icon.png" },  // iOS icon
    { rel: "icon", type: "image/png", sizes: "192x192", url: "/android-chrome-192x192.png" }, // Android 192x192
    { rel: "icon", type: "image/png", sizes: "512x512", url: "/android-chrome-512x512.png" }, // Android 512x512
  ],
  manifest: "/site.webmanifest", // Link to the Web App Manifest for Android
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html >
      <body>
  
      <Suspense fallback={<p>Loading...</p>}>
        <Script strategy="beforeInteractive"
          id="facebook-pixel"
          // Ensures script is loaded after the page is interactive
          dangerouslySetInnerHTML={{
            __html: `
            !function(f,b,e,v,n,t,s)
            {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
            n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t,s)}(window, document,'script',
            'https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', '575276985320409');
            fbq('track', 'PageView');
          `,
          }}
        />
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=575276985320409&ev=PageView&noscript=1"
          />
        </noscript>

        <CartProvider>
          <ToastContainer
            position="top-right"
            autoClose={1000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
            transition={Slide}
          />
          <Header />

          <div>
            {children}
            <Analytics />
          </div>
          <Footer />
        </CartProvider>
        </Suspense>
      </body>
    </html>
  );
}
